### ISSUE TITLE
Dockerignore syntax recognition

### ISSUE THREAD

**Issue by Angelk90** [eth0net/zed-docker-compose#1]
Hi @eth0net , It would also be possible to do the dockerignore syntax recognition

<img width="305" alt="Screenshot 2024-04-23 alle 11 50 05" src="https://github.com/eth0net/zed-docker-compose/assets/20476002/b98f9767-5121-4856-966e-8bf80e8d8d47">

**Comment by eth0net** [comment]
Dockerignore is now handled under the git-firefly extension 😃
